#####################################################################################
#   Experiment Configuration -    #
#####################################################################################

name: "simple"
desc: "a simple experiment"

settings:
    debug: true # set to false for production

trials: # each trial changes the parameters it chooses - this is later merged with the trials.yaml

